### ISSUE TITLE
Update to SDK 3.0

### ISSUE THREAD

**Issue by Sneaky42** [Erumite/Eremite_VRC#2]
Greetings, Looking to see if there is a way to purchase an updated version of the Drone for SDK 3.0

**Comment by Erumite** [comment]
Hey, I haven't gotten around to doing a lot of avatar stuff for SDK3 yet.  It's actually *much* simpler to do nearly all the weird avatar hacks in this repository on SDK3. 

This isn't mine, but I found this by searching for drones on booth: https://booth.pm/ko/items/2558595
